// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAuVVhm6TaqKff79TXOw_RCvT6DFb9uEcM',
    appId: '1:255230633950:web:e4d2752e490fb38fd21f4f',
    messagingSenderId: '255230633950',
    projectId: 'rafael-barber-shop',
    authDomain: 'rafael-barber-shop.firebaseapp.com',
    storageBucket: 'rafael-barber-shop.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxwccSceTKG2cwrEm150Dj23KY1WfAH7k',
    appId: '1:255230633950:android:c745c2e8f7338b3bd21f4f',
    messagingSenderId: '255230633950',
    projectId: 'rafael-barber-shop',
    storageBucket: 'rafael-barber-shop.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2_yRMGWk3K3g1Cx1tPMgjNq0LodM1w-o',
    appId: '1:255230633950:ios:6b21fd15c941d953d21f4f',
    messagingSenderId: '255230633950',
    projectId: 'rafael-barber-shop',
    storageBucket: 'rafael-barber-shop.appspot.com',
    iosBundleId: 'com.example.rafaelBarbershopApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2_yRMGWk3K3g1Cx1tPMgjNq0LodM1w-o',
    appId: '1:255230633950:ios:0083dd8b41130b32d21f4f',
    messagingSenderId: '255230633950',
    projectId: 'rafael-barber-shop',
    storageBucket: 'rafael-barber-shop.appspot.com',
    iosBundleId: 'com.example.rafaelBarbershopApp.RunnerTests',
  );
}
